Updated mediawiki/extensions Project: mediawiki/extensions/Popups  b65954645f6cb90a3dde12717071a47c7abe1d87
Check for empty response

In combination with other gadgets the error
TypeError: re.query is undefined
can occur because the request contains titles:'' and the response is [].

Change-Id: I46d02e7c48a55cd9af20fd7ef729b4d26f69a8c0