Update git submodules
* Update FlaggedRevs from branch 'master'
  to bbdfc4c024a9bc88bcb38067a411fbcb2576a128
  - FlaggedRevsUIHooks: Migrate remaining hooks to newFromTitle
    
    Follows-up 6bfd276e64 and 5ee96e5ca7. This should fix the CI failure
    in CentralAuth where FR onBeforePageDisplay() hook crashed during an
    integration test that called OutputPage::output() because the injected
    context had a valid title, so canExist=true, but then the next call
    to ::singleton here explodes as the global title was still null as
    it always has been during integration tests.
    
    ```
    1) CentralAuthApiSessionProviderTest::testUserScriptsDisabled
    TypeError: Argument 1 passed to FlaggablePageView::newFromTitle() must
    implement interface MediaWiki\Page\PageIdentity, null given
    /extensions/FlaggedRevs/frontend/FlaggablePageView.php:56
    /extensions/FlaggedRevs/frontend/FlaggablePageView.php:74
    /extensions/FlaggedRevs/frontend/FlaggedRevsUIHooks.php:94
    ```
    
    FlaggablePageView::singleton() is no longer used in FR, but is kept
    for one commit because during the transition for T314008 in
    VisualEditor involved introducing a call to the singleton *inside*
    the ApiVisualEditorEdit class. Until that's removed, the method will
    have to stay here a little bit longer.
    
    Bug: T314008
    Change-Id: I04fdbd497b835f19436de5454000126c24824256