Update git submodules
* Update Convert2Wiki from branch 'master'
  - Inline endsWith function
    
    Jenkins fails with:
    Fatal error: Function already defined: endsWith in
    /home/jenkins/workspace/mwext-testextension-hhvm-jessie/src/LocalSettings.php
    on line 304
    
    Change-Id: I4689b658701dfcf15da68d2427d9d456b1d338f6