Remove duplicate submodule definitions
Causes git submodule updates to fail with a cryptic:
  error: invalid key (newline): submodule.Ipernity
   Ipernity.url
  error: invalid key (newline): submodule.Ipernity
   Ipernity.url
  No url found for submodule path 'Ipernity' in .gitmodules

Side effect is LocalizationUpdate not updating.

Bug: 60860
Change-Id: I0b1f44c7129d65d202d483aa88610dfc3bfa94c3