Update git submodules
* Update Wikisource from branch 'master'
  to 59abd6d46140fd49165f57968ad85e8443bd10bb
  - Merge "Add mediawiki.api dependency to ext.wikisource.OCR"
  - Add mediawiki.api dependency to ext.wikisource.OCR
    
    OcrTool.js is using mw.Api (since b4f29d2d64)
    
    qunit tests shows sometimes:
    Uncaught TypeError: api.saveOption is not a function
    
    Change-Id: Ib8276e203d13849b321b161d626df71dc773874b