Update git submodules
* Update MobileFrontend from branch 'master'
  - Merge "Remove unused mw.mobileFrontend reference"
  - Remove unused mw.mobileFrontend reference
    
    As part of fixing linting errors
    https://gerrit.wikimedia.org/r/#/c/312850/ and
    https://integration.wikimedia.org/ci/job/mwext-MobileFrontend-npm-run-lint-modules/18/console
    
    Error: Dependency problems in file:
      resources/mobile.special.userlogin.scripts/userlogin.js:
        Required mw.mobileFrontend defined in file
        resources/mobile.modules/modules.js not found in any ResourceModules
    
    Change-Id: I2b5416aa512d39389a0055edf56ba6819fb28583