Update git submodules
* Update GlobalWatchlist from branch 'master'
  to 756faba82217892f836abfea732c1e57efbd5ed0
  - SiteDisplay.afterMarkAsSeen check if $feedDiv is set
    
    If its an empty string from not having any changes,
    it causes a TypeError: this.$feedDiv.children is not a function
    
    Bug: T275078
    Change-Id: I0e638187716a1517a606addcbf4d21fb2c00a694