Update git submodules
* Update GrowthExperiments from branch 'master'
  to a9d0ae06284c8be31d4e66d8042d7e42857d266d
  - tests(Cypress): try to fix "center of element is hidden"-error
    
    The Template-based tasks cypress test is flaky with on the last test the
    typing failing with:
    
    ```
    CypressError: Timed out retrying after 20000ms: `cy.type()` failed because the center of this element is hidden from view:
    
    `<div class="ve-ce-branchNode ve-ce-documentNode ve-ce-attachedRootNode ve-ce-rootNode mw-content-ltr mw-parser-output mw-show-empty-elt" contenteditable="true" spellcheck="true" tabindex="0" data-gramm="false" role="textbox" lang="en" dir="ltr">...</div>`
    
    ```
    
    This change tries to address that by making that article shorter.
    
    If that doesn't reliably fix the flakyness, we can try adding
    `{ force: true }` to the type command.
    
    Change-Id: I14660ebf11b914b7f02bf636ca086284fcd00327