Update git submodules
* Update ReplaceText from branch 'master'
  to 0ed04eea342d2de4dac5a0b57ba3c18836291f35
  - Merge "build: Remove syntax option from stylelint"
  - build: Remove syntax option from stylelint
    
    Error: The "syntax" option is no longer available. You should install an
    appropriate syntax, e.g. postcss-scss, and use the "customSyntax" option
    
    Change-Id: I43a39d8238143e02e9ba3ba2ee3652a63d3d6921