Update git submodules
* Update ORES from branch 'master'
  to 62125d4a38f51d81a6a520b6710a5f3c6e4f2ab0
  - Fix watchlist API
    
    The query has been giving out fatals because ores_model is not being used
    directly anymore causing it to join with the wrong table:
    SELECT [...] FROM `recentchanges`,`ores_model`
    JOIN `watchlist` ON ((wl_namespace=rc_namespace) AND (wl_title=rc_title))
    LEFT JOIN `page` ON ((rc_cur_id=page_id))
    INNER JOIN `ores_classification`
    ON ((rc_this_oldid=oresc_rev) AND oresc_model = '49' AND oresc_class = '1')
    WHERE ...
    
    Erroring with:
    Error: 1054 Unknown column 'rc_namespace' in 'on clause'
    
    Also added regression tests.
    
    Bug: T210638
    Change-Id: Idfea09732e0f86c50da4cd88a61916f9bc7f9dcd