Update git submodules
* Update MobileFrontend from branch 'master'
  - Merge "ReferencesMobileViewGateway depends on mw.Api"
  - ReferencesMobileViewGateway depends on mw.Api
    
    ReferencesMobileViewGateway.getSingleton uses mw.Api but that wasn't
    found in the dependency tree of the module explicitly.
    
    Fixes linting error from https://gerrit.wikimedia.org/r/#/c/312850/ and
    https://integration.wikimedia.org/ci/job/mwext-MobileFrontend-npm-run-lint-modules/18/console
    
    Error: Dependency problems in file: resources/mobile.references.gateway/ReferencesMobileViewGateway.js:
      Required mw.Api defined in file resources/src/mediawiki/api.js not found in any ResourceModules
    
    Change-Id: Ie09722d838b3aa37b0f127fc942caa9c2a64f0f0