Update git submodules
* Update Translate from branch 'master'
  to fd8fba8fee2dea3d9a8f1ac2e832abd06225ce40
  - WorkflowStatesMessageGroup: Fetch state content only if group has them
    
    On my local machine, I initially did not have message group states
    enabled, and enabled them later. I had many groups without states.
    
    Trying to delete a page, I get the following error:
    
    InvalidArgumentException: Wikimedia\Rdbms\Platform\SQLPlatform::makeList: empty input for field page_title
    
    which is from the call to:
    
    Utilities::getContents( array_keys( $keys ), $this->getNamespace() )
    
    from WorkflowStatesMessageGroup::getDefinitions
    
    Change-Id: I588203734e487a50a179900680675124cdce325b