Update git submodules
* Update Translate from branch 'master'
  to 96735eb6bec6510bbdcbc788bcf638da4b447d05
  - Destroy cdb reader in MessageChangeStorage::writeGroupChanges
    
    Running tests under Windows shows errors, for example:
    1) MediaWiki\Extension\Translate\MessageGroupProcessing\ManageMessageGroupsActionApiTest::testRename
    Error: DBA connection has already been closed
    
    Caused by
    PHPUnit\Framework\Error\Warning:
    rename(tmp\MW_C123.tmp/messagechanges.default.cdb.tmp.640430838,tmp\MW_C123.tmp/messagechanges.default.cdb):
    Access is denied. (Error code: 5)
    
    The rename() is called in Writer\DBA::close() from package
    wikimedia/cdb, but fails due to open file handle on the target file.
    
    Destroying the reader closes the file handle and
    allows the writer to replace the target file.
    
    Change-Id: Ifb2e66a91ce5c8db5b308354627a581af3bfca3d