Update git submodules
* Update MobileFrontend from branch 'master'
  to b91e0e666b9ad78a7bdf81e5ba6835382156d368
  - Fixes TypeError: e.(on|off) is not a function
    
    This is occurring in production at a low rate.
    There is no hard in hardening this function
    
    If the stack has an item which has no overlay associated, then
    there is nothing to hide.
    
    Change-Id: Ie711bf18af242139a89f0721575d8565988f1295