Updated mediawiki/extensions Project: mediawiki/extensions/OAuth  0b98899d33ac8ebc5456f92dfedce90bea6c0e43
Add missing \ to Title

Fatal error:  Class 'MediaWiki\Extensions\OAuth\Title' not found in
OAuth/frontend/specialpages/SpecialMWOAuth.php on line 210

Change-Id: I929d8afd326dbf4467be3bd276b19f2758292fb1