Update git submodules
* Update Echo from branch 'master'
  to 0a9811b3d02f5c4280324ea6ac3d3d95a19eb837
  - Merge "Do not recreate echo_event.event_page_namespace on sqlite update"
  - Do not recreate echo_event.event_page_namespace on sqlite update
    
    column event_page_namespace was dropped from the database
    When running the updater for sqlite on a fresh install it fails
    Function: Wikimedia\Rdbms\Database::sourceFile(
    /workspace/src/extensions/Echo/db_patches/patch-event_variant_nullability.sqlite.sql
    )
    Error: 1 no such column: event_page_namespace
    
    
    Change-Id: I397e601dd9db45fc34669c43df5f9dd8d337ed95