Update git submodules
* Update VEForAll from branch 'master'
  to f80555b1006eba3656f235ac2aab2c4742c6833a
  - Change base class of mw.veForAll.Target for mw 1.32+
    
    mw.veForAll.Target should be based on ve.init.mw.Target instead of
    ve.init.sa.Target since MediaWiki 1.32, in other case it breaks some things, for example when
    you insert an image you get an exception:
    "TypeError: ve.init.target.getContentApi is not a function"
    and others more specific issues
    
    Change-Id: I864c2fe091e432473ea4db4e378ed478c7d1fc15