Updated mediawiki/extensions Project: mediawiki/extensions/PageImages  1690d99e369dbac3c7e11cf61a1b9e42d62150f6
Revert "Include foreign files in ApiQueryPageImages"

Fatal error: Invalid operand type was used: cannot perform this operation with arrays

This reverts commit 47137e7ee671c89667d620bc04ac7649b1d9af96.

Bug: T114417
Change-Id: I89a2bfd69775a698f3000f48ea85465e193fb095