Update git submodules
* Update Popups from branch 'master'
  to 5872c8376def604cd4d8b0a11c54d080c661174a
  - Fix: JSDoc Node.js file copy bug
    
    Upgrade JSDoc from v3.4.3 to 3.5.5:
    - v3.5.0 JSDoc can parse any JavaScript that is supported by Babel
      compiler.
    - v3.5.1 fixes an incompatibility bug in Node.js < v5.10.0
    - v3.5.5 fixes an incompatibility bug in Node.js v8.5.0
    
    Prior to this change, object shorthand caused the following errors:
    
      jsdoc -c jsdoc.json
      fs.js:1979
        binding.copyFile(src, dest, flags);
                ^
    
      Error: EISDIR: illegal operation on a directory, copyfile '/home/stephen/dev/wmf/vagrant2/mediawiki/extensions/Popups/node_modules/jsdoc/templates/default/static/fonts/OpenSans-Bold-webfont.eot' -> 'doc/autogenerated/fonts'
          at Object.fs.copyFileSync (fs.js:1979:11)
          at /home/stephen/dev/wmf/vagrant2/mediawiki/extensions/Popups/node_modules/jsdoc/templates/default/publish.js:471:12
          at Array.forEach (<anonymous>)
          at Object.exports.publish (/home/stephen/dev/wmf/vagrant2/mediawiki/extensions/Popups/node_modules/jsdoc/templates/default/publish.js:468:17)
          at Object.module.exports.cli.generateDocs (/home/stephen/dev/wmf/vagrant2/mediawiki/extensions/Popups/node_modules/jsdoc/cli.js:430:39)
          at Object.module.exports.cli.processParseResults (/home/stephen/dev/wmf/vagrant2/mediawiki/extensions/Popups/node_modules/jsdoc/cli.js:383:20)
          at module.exports.cli.main (/home/stephen/dev/wmf/vagrant2/mediawiki/extensions/Popups/node_modules/jsdoc/cli.js:227:14)
          at Object.module.exports.cli.runCommand (/home/stephen/dev/wmf/vagrant2/mediawiki/extensions/Popups/node_modules/jsdoc/cli.js:180:5)
          at /home/stephen/dev/wmf/vagrant2/mediawiki/extensions/Popups/node_modules/jsdoc/jsdoc.js:103:9
          at Object.<anonymous> (/home/stephen/dev/wmf/vagrant2/mediawiki/extensions/Popups/node_modules/jsdoc/jsdoc.js:104:3)
          at Module._compile (module.js:662:30)
          at Object.Module._extensions..js (module.js:673:10)
          at Module.load (module.js:575:32)
          at tryModuleLoad (module.js:515:12)
          at Function.Module._load (module.js:507:3)
          at Function.Module.runMain (module.js:703:10)
    
    https://github.com/jsdoc3/jsdoc/releases/tag/3.5.0
    https://github.com/jsdoc3/jsdoc/releases/tag/3.5.1
    https://github.com/jsdoc3/jsdoc/releases/tag/3.5.2
    https://github.com/jsdoc3/jsdoc/releases/tag/3.5.3
    https://github.com/jsdoc3/jsdoc/releases/tag/3.5.4
    https://github.com/jsdoc3/jsdoc/releases/tag/3.5.5
    
    Bug: T165036
    Change-Id: Ic7a22b6992d45fa0ea3d011a9ad5200d7cc73b80