Update git submodules
* Update TheWikipediaLibrary from branch 'master'
  to cbbabb6150bd39e472d23dbb47999b982958e13b
  - tests: skip Echo tests when it is not loaded
    
    When Echo is not loaded (it is not required in extension.json), an
    integration test will fail:
    
      1) TheWikipediaLibraryEchoTest::testNoDupes
      Error: Class "MediaWiki\Extension\Notifications\DbFactory" not found
    
    Skip it when Echo is not loaded.
    
    Bug: T410118
    Change-Id: If5334c22206933242c895ec5ea377c35c58530ab