Update git submodules
* Update BlueSpiceFoundation from branch 'master'
  to 7c3f5b0043b56c80dae2c4b1a8f90381d863076c
  - tests: Add Database group
    
    LogicException: Test users get persisted in the test database and can
    only be used in tests having `@group Database`. Add this test to the
    Database group or, preferably, construct or mock a
    UserIdentity/Authority if the test doesn't need a real user account.
    
    Change-Id: I602e05ad14d7ca1a385a3d174de0d7e19b4ebb08