Update git submodules
* Update Wikibase from branch 'master'
  to bf95ae558f2561b435f11d1600257f30763e7481
  - Use HHVM 3.24 on travis
    
    Travis switched to HHVM 3.25 today and this breaks the
    MediaWiki installer:
    https://travis-ci.org/wikimedia/mediawiki-extensions-Wikibase/jobs/354066111
    
    php maintenance/install.php --dbtype mysql --dbuser root --dbname its_a_mw --dbpath /home/travis/build/wikimedia/phase3 --pass nyan TravisWiki admin
    HHVM 3.25.0 is installed.
    …
    Fatal error: Uncaught TypeError: Argument 3 to mysqli::real_connect() must be of type ?string, bool given in /home/travis/build/wikimedia/phase3/includes/libs/rdbms/database/DatabaseMysqli.php:115
    
    Change-Id: Ia51c890190248c2165ff462def403d8f0d9b5f84