Updated mediawiki/extensions Project: mediawiki/extensions/Collection  bf7c4b968d1464d8a44a6924aaf3ee6578552d7a
Fatal error: Unsupported operand types in Collection.body.php

Bug: 60538
Change-Id: I7c783693a07110d1b94267cbbcfc3822e1609585
(cherry picked from commit 7df4721a7e2f282c14720146042002e271bd9cd8)