Update git submodules
* Update BlueSpiceWikiFarm from branch 'master'
  to d549738cd1df66effb37ce0e51fa9e903b16ec6a
  - Special: Use `::setPageTitleMsg()` instead of `::setPageTitle()`
    
    In MediaWiki 1.45, the use of setPageTitle() with localization
    messages was no longer allowed. An equivalent method was introduced
    to handle this.
    
    This fixes an an error when trying to create a new wiki using the
    `Special:FarmManagement` feature. Without this patch on REL1_47,
    trying to create a wiki fails with the below error:
    
    ```
    ParameterTypeException: Bad value for parameter $name: must be a string
    ```
    
    Test plan
    =========
    1. On a given wiki, visit: `<wiki-url>/wiki/Special:Farm_management`
    2. Click on the "Create wiki" button
    3. Follow the next steps as required
    
    [galaxy]
    
    ERM50206
    
    Change-Id: I779772ae29298e69b86d73c743cfb6d4b3b6dfc3