Update git submodules
* Update Wikibase from branch 'master'
  to eec431089c0b54bc627c05e77e257315299b16a4
  - tests: Avoid assert outside test flow (ChangeModification, EntityDataPurger)
    
    * Adopt assertArrayContains() to simplify code and improve debug
      experience (complete diff, instead of first/single failure only
      of a single key).
    
    * Move assertion out of mock function to keep verification flow
      contained in the main test function. This also avoids the need for
      added complexity in the test (which was nearing the level where
      one might want a unit test to verify that the test is written
      correctly), where it's very easy to get to a point where the test
      is passing because the code wasn't executed or executed too often.
      Instead, let the mock be responsible for what it should be (fulfill
      source code expectations), and the test function for what it should
      (verify expected outcome). This should also make the test less
      unintentinally opinionated about implementation details.
    
    * Simplify "zero jobs" expectation using an empty array, also allows
      logic to be unified across the two test cases.
    
    * Remove bad return value from "lazyPush" stub, should return void.
    
    * Switch from plain PHPUnit TestCase to MediaWikiUnitTestCase,
      and fix the two violations of pure unit tests that previously went
      undetected:
      > LogicException: Premature access to service container
      via Title::newFromText -> …  -> MediaWikiServices->getTitleParser
    
    Change-Id: I71b68f34d95b730fd06104688db021f48a4651a5