Updated git submodules
Project: mediawiki/extensions/Flow REL1_27 2fb479ca3a6f484f99abaa38812d63a38b91c1d1

Drop and re-create the index

MySQL will give an error if you just change to a blob
    Error: 1170 BLOB/TEXT column 'ref_target' used in key specification without a key length

Bug: T110446
Change-Id: Icfc080768005a314970498e94861a1ab9c068549
(cherry picked from commit 5bf7057a1a01967aa05f6296cf850587ffedb419)