Update git submodules
* Update BlueSpiceWikiFarm from branch 'master'
  to 5704474b8918e1b6ab498fa3e35e6a526b911ff2
  - Add missing service to ObjectFactory spec
    
    Fixes
    TypeError: BlueSpice\WikiFarm\Process\Step\ArchiveInstance::__construct(): Argument #3 ($storageHandler) must be of type MWStake\MediaWiki\Component\FileStorageUtilities\StorageHandler, string given, called in vendor/wikimedia/object-factory/src/ObjectFactory.php on line 220
    Backtrace:
    from extensions/BlueSpiceWikiFarm/src/Process/Step/ArchiveInstance.php(46)
    ...
    
    ERM48053
    [5.x]
    
    Change-Id: Ic69b5ef6de732127e4dbc28bab997e3d66396734