Updated mediawiki/extensions Project: mediawiki/extensions/CategoryTree  8d7de84017d3f8efb6bfb5265665aa4907767cde
Register CategoryTreeMagic from global scope instead of setup

Follows-up I32357244c013a2370f14f.

I don't know how or why, but this late way of registering magic
words from within an extension setup function is sometimes
causing people's install to fatally crash on:

> Exception from line 318 of mw/includes/MagicWord.php:
>   Error: invalid magic word 'categorytree'

Just move it out of there into a plain and simple registration.

The parser function itself is still registered conditionally.

Change-Id: I07df5de5f39ce0ad029ef0152d126e620308ba25