Update git submodules
* Update OpenID from branch 'master'
  to 359c76eebee440218fdc4a8cf3bbb0ddb8eb3be7
  - Avoid null $wgAuth given to method_exists
    
    TypeError: method_exists(): Argument #1 ($object_or_class) must be of
    type object|string, null given on php8.0
    
    json_decode(): Passing null to parameter #1 ($json) of type string is
    deprecated in php8.1
    
    Change-Id: I64a5110071f692559a6193a84c5dfb1ace01b39b