Update git submodules
* Update DisplayTitle from branch 'master'
  to ea9e1248936aee562e8a754ce63222e38163a0ae
  - Fix test error
    
    Error: Call to undefined method MediaWiki\Parser\ParserOutput::getText()
    Requires dropping support for MW 1.42-
    
    Change-Id: I636bd1f1988693d24e135b1f397cfe17e2b0102e