Update git submodules
* Update CommunityConfiguration from branch 'master'
  to 1489002b3c1c70f68dad04050e222f759695350f
  - fix(editor): fix ClientErrorMessage by using `$i18n` in template
    
    The snapshot test should be good enough as there is basically no logic
    involved in this component. The main thing that this test asserts is
    that no error message is being called with something like:
    "TypeError: _ctx.i18n is not a function"
    
    Change-Id: I453ec68faa3ab72ba83c7c204738d60d10092087