Update git submodules
* Update VisualEditorPlus from branch 'master'
  to 85b4190009e810973cbc81a8821737eabddb468c
  - Add missing dependency
    
    Exception in module-execute in module ext.visualEditorPlus.tags.definition:
    ReferenceError: OO is not defined at Definition.js:47:1
    
    ERM29303
    
    [5.1.x]
    
    Change-Id: I9d3afaf8c3241816c3e0b08605697da29632b337
    (cherry picked from commit b5371c5faaa9ae2dd1138aa34e8ad9282a1003f3)
    (cherry picked from commit fd1729eff0c39c19a7e5e26ba678e561f097a250)