Update git submodules
* Update Translate from branch 'master'
  to 31b9760dc549581ff1aefe1e5fbf3297fc25bbcd
  - SearchTranslationsSpecialPage: Handle document with null content
    
    Fixes error:
    
    TypeError: Argument 1 passed to MediaWiki\Extension\Translate\Utilities\Utilities::convertWhiteSpaceToHTML() must be of the type string, null given
    
    Due to data corruption sometimes the documents fetched may not have
    any content.
    
    Change-Id: I0910a52ee3d1a4b6f8e068eb7497acee5221ab8b