Update git submodules
* Update WikiEditor from branch 'master'
  to 760f023f2145ed5b86e1ce7328fce6c56a30296a
  - TypeError: $button.trigger is not a function
    
    This error is generating a large amount of logspam.
    Add a check to avoid it, and DRY up.
    
    The issue is caused by line 1182 setting dialogaction to false when
    a dialog is closed. Presumably references to this data attribute
    remain.
    
    Bug: T261529
    Change-Id: Ie75f737980dfcbcc4829def1e5a6894262d73b31