Update git submodules
* Update MediaWikiChat from branch 'master'
  to 2da8945dea2d2c45d3a36add3bd9e6695bb8828f
  - Fix the UserGroupsChanged hook handler for autopromotions
    
    This was causing a TypeError to be logged when some autopromote conditions were set in LocalSettings.php.
    
    The autopromote conditions I had ("borrowed" from Uncyclopedia's config files):
    
    $wgAutopromoteOnce['onEdit']['extendedconfirmed'] = [
    	'&',
    	[ APCOND_EDITCOUNT, 500 ],
    	[ APCOND_AGE, 30 * 86400 ], // 30 days * seconds in a day
    ];
    
    $wgGroupPermissions['bot']['extendedconfirmed'] = true;
    $wgGroupPermissions['sysop']['extendedconfirmed'] = true;
    $wgGroupPermissions['sysadmin']['extendedconfirmed'] = true;
    $wgGroupPermissions['extendedconfirmed']['extendedconfirmed'] = true;
    
    Stack trace:
    
    TypeError: MediaWikiChatHooks::onUserGroupsChanged(): Argument #4 ($performer) must be of type User, bool given, called in /var/www/html/mediawiki-1.43.0/includes/HookContainer/HookContainer.php on line 159
    0 /var/www/html/mediawiki-1.43.0/includes/HookContainer/HookContainer.php(159): MediaWikiChatHooks::onUserGroupsChanged()
    1 /var/www/html/mediawiki-1.43.0/includes/HookContainer/HookRunner.php(4355): MediaWiki\HookContainer\HookContainer->run()
    2 /var/www/html/mediawiki-1.43.0/includes/user/UserGroupManager.php(721): MediaWiki\HookContainer\HookRunner->onUserGroupsChanged()
    3 /var/www/html/mediawiki-1.43.0/includes/Storage/PageUpdater.php(939): MediaWiki\User\UserGroupManager->addUserToAutopromoteOnceGroups()
    4 /var/www/html/mediawiki-1.43.0/includes/deferred/MWCallableUpdate.php(52): MediaWiki\Storage\PageUpdater->MediaWiki\Storage\{closure}()
    5 /var/www/html/mediawiki-1.43.0/includes/deferred/DeferredUpdates.php(460): MediaWiki\Deferred\MWCallableUpdate->doUpdate()
    6 /var/www/html/mediawiki-1.43.0/includes/deferred/DeferredUpdates.php(204): MediaWiki\Deferred\DeferredUpdates::attemptUpdate()
    7 /var/www/html/mediawiki-1.43.0/includes/deferred/DeferredUpdates.php(291): MediaWiki\Deferred\DeferredUpdates::run()
    8 /var/www/html/mediawiki-1.43.0/includes/deferred/DeferredUpdatesScope.php(243): MediaWiki\Deferred\DeferredUpdates::MediaWiki\Deferred\{closure}()
    9 /var/www/html/mediawiki-1.43.0/includes/deferred/DeferredUpdatesScope.php(172): MediaWiki\Deferred\DeferredUpdatesScope->processStageQueue()
    10 /var/www/html/mediawiki-1.43.0/includes/deferred/DeferredUpdates.php(285): MediaWiki\Deferred\DeferredUpdatesScope->processUpdates()
    11 /var/www/html/mediawiki-1.43.0/includes/MediaWikiEntryPoint.php(674): MediaWiki\Deferred\DeferredUpdates::doUpdates()
    12 /var/www/html/mediawiki-1.43.0/includes/MediaWikiEntryPoint.php(496): MediaWiki\MediaWikiEntryPoint->restInPeace()
    13 /var/www/html/mediawiki-1.43.0/includes/MediaWikiEntryPoint.php(454): MediaWiki\MediaWikiEntryPoint->doPostOutputShutdown()
    14 /var/www/html/mediawiki-1.43.0/includes/MediaWikiEntryPoint.php(209): MediaWiki\MediaWikiEntryPoint->postOutputShutdown()
    15 /var/www/html/mediawiki-1.43.0/index.php(58): MediaWiki\MediaWikiEntryPoint->run()
    16 {main}
    
    Change-Id: I7983a3718cac1817963627156569ec572442ad7e