Update git submodules
* Update TemplateData from branch 'master'
  to d253fa4e28d099d6e93480563fdcbe3d309779ae
  - Merge code paths in assertTemplateData() helper method
    
    This streamlines the code of the helper method a bit, mostly by
    avoiding duplication.
    
    What actually happens is the exact same as before, with one
    exception: When a test case doesn't have an expected "output",
    the default (mostly empty) output does not run through the
    roundtrip test. While doing this is not wrong, it doesn't tell
    us anything about the specific test case.
    
    Change-Id: I4a3d8a22c3dd6a9c5c3766195e5aef3cf37a6441