Updated mediawiki/extensions Project: mediawiki/extensions/Translate  fd127213e6cc9fc8481378295c44b60c330e2aa7
Revert "Readd formatMessageBeforeTable hook"

Caused:
TypeError: mw.translateHooks is undefined
https://translatewiki.net/w/extensions/Translate/resources/js/ext.translate.messagetable.js
Line 130

This reverts commit 2b7bd314349432d96017e7495027b37a013e89a3

Change-Id: Iefffd8c6cc87587e45ec1fc0810b77470625c23b